const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
const root=require('node:path').join(__dirname,'../dist/');
function setup(saved){const dom=new JSDOM(fs.readFileSync(root+'index.html','utf8'),{url:'https://navos.test/',runScripts:'outside-only'});const w=dom.window;w.matchMedia=()=>({matches:true});w.Audio=class{play(){return Promise.resolve()}pause(){}};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};if(saved)w.sessionStorage.setItem('navos.session.v1',saved);w.eval(fs.readFileSync(root+'xp.js','utf8'));return dom}
const d=setup(),w=d.window,$=s=>w.document.querySelector(s),click=s=>$(s).click();
assert.ok($('#create-user'));click('#create-user');assert.equal($('#user-dialog').open,true);$('#guest-name').value='<b>Nav guest</b>';$('#guest-avatar').value='people';$('#guest-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal($('#guest-profiles strong').textContent,'<b>Nav guest</b>');assert.equal($('#guest-profiles strong b'),null);assert.equal($('#user-dialog').open,false);click('#guest-profiles button');assert.equal($('#desktop').hidden,false);assert.equal($('#start-user-name').textContent,'<b>Nav guest</b>');
click('#properties');let section=$('.display-window');assert.ok(section);assert.equal(section.querySelector('[data-wallpaper=bliss]').getAttribute('aria-pressed'),'true');section.querySelector('[data-wallpaper=blue]').click();section.querySelector('[data-cancel]').click();assert.equal($('.wallpaper').hidden,false);
click('#properties');section=$('.display-window');section.querySelector('[data-wallpaper=blue]').click();section.querySelector('[data-apply]').click();assert.equal($('.wallpaper').hidden,true);section.querySelector('[data-ok]').click();click('#log-off');click('#xp-profile');assert.equal($('.wallpaper').hidden,false);click('#log-off');click('#guest-profiles button');assert.equal($('.wallpaper').hidden,true);
const saved=w.sessionStorage.getItem('navos.session.v1');assert.equal(JSON.parse(saved).guests.length,1);const restored=setup(saved);assert.equal(restored.window.document.querySelector('#guest-profiles strong').textContent,'<b>Nav guest</b>');restored.window.close();const fresh=setup();assert.equal(fresh.window.document.querySelector('#guest-profiles').children.length,0);fresh.window.close();
click('#user-accounts');$('#guest-name').value='<b>Nav guest</b>';$('#guest-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.match($('#user-error').textContent,/already/);click('#temporary-users button');assert.equal($('#welcome').hidden,false);assert.equal($('#guest-profiles').children.length,0);d.window.close();console.log('Passed: guest creation, literal-name rendering, duplicate protection, wallpaper Apply/Cancel, per-profile isolation, session restore/reset, current guest removal.');
